Boolean Use Non BAU ZEV Qualifying Vehicle Definitions = 1
Minimum Required ZEV Sales Percentage[passenger,LDVs] = 1
Minimum Required ZEV Sales Percentage[passenger,HDVs] = 0.95
Minimum Required ZEV Sales Percentage[freight,LDVs] = 1
Minimum Required ZEV Sales Percentage[freight,HDVs] = 0.78
Percentage Additional Improvement of Fuel Economy Std[passenger,HDVs] = 0.3224
Percentage Additional Improvement of Fuel Economy Std[freight,HDVs] = 0.29
Policy Implementation Schedule Selector = 2
